# Generated by Django 4.1.1 on 2022-09-26 14:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('creation_date', models.DateField(auto_now=True)),
                ('closed', models.BooleanField(default=False)),
                ('due_date', models.DateField(default=datetime.date(2022, 9, 26))),
                ('schedule_date', models.DateField(default=datetime.date(2022, 10, 3))),
            ],
        ),
    ]
