# Generated by Django 4.1.1 on 2022-09-26 15:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesTaches', '0002_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2022, 9, 26, 15, 9, 4, 158, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='task',
            name='schedule_date',
            field=models.DateField(default=datetime.datetime(2022, 10, 3, 15, 9, 4, 158, tzinfo=datetime.timezone.utc)),
        ),
    ]
