# Generated by Django 4.1.1 on 2022-09-26 15:09

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lesTaches', '0003_alter_task_due_date_alter_task_schedule_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='task',
            name='schedule_date',
            field=models.DateField(default=datetime.datetime(2022, 10, 3, 15, 9, 35, 520346, tzinfo=datetime.timezone.utc)),
        ),
    ]
