# Generated by Django 4.1.1 on 2022-09-26 15:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesTaches', '0004_alter_task_due_date_alter_task_schedule_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
        migrations.AlterField(
            model_name='task',
            name='schedule_date',
            field=models.DateField(default=datetime.datetime(2022, 10, 3, 15, 11, 17, 663260, tzinfo=datetime.timezone.utc)),
        ),
    ]
