# Generated by Django 4.1.1 on 2022-09-26 15:19

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lesTaches', '0005_rename_users_user_alter_task_schedule_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='owner',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='lesTaches.user'),
        ),
        migrations.AlterField(
            model_name='task',
            name='schedule_date',
            field=models.DateField(default=datetime.datetime(2022, 10, 3, 15, 19, 42, 485343, tzinfo=datetime.timezone.utc)),
        ),
    ]
