# Generated by Django 4.1.1 on 2022-09-26 16:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesTaches', '0006_task_owner_alter_task_schedule_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateField(default=datetime.date(2022, 10, 3)),
        ),
        migrations.AlterField(
            model_name='task',
            name='schedule_date',
            field=models.DateField(null=True),
        ),
    ]
